baseURL = 'saetron.github.io/visualnovelwiki/'
languageCode = 'en-us'
title = 'Visual Novel Wiki'
theme = 'hugo-theme-relearn'

[params]
  themeVariant = 'zen-dark'
  disableNextPrev = true
  collapsibleMenu = true
  disableBreadcrumb = true
  ordersectionsby = 'linktitle'

