baseURL = 'www.vnwiki.xyz/'
languageCode = 'en-us'
title = 'Visual Novel Wiki'
theme = 'hugo-theme-relearn'
enableRobotsTXT = true

[params]
  themeVariant = 'zen-dark'
  disableNextPrev = true
  collapsibleMenu = true
  disableBreadcrumb = true
  ordersectionsby = 'linktitle'

[sitemap]
  changeFreq = 'monthly'
